name = "daily-business-ideas-bot"
main = "src/index.mjs"
compatibility_date = "2026-04-01"

[[kv_namespaces]]
binding = "BOT_KV"
id = "d1edb794ea3442a790d4e9e69127a5ca"

[vars]
GITHUB_REPO = "animuradyanartist/daily-business-ideas"
ALLOWED_CHAT_ID = "1010175368"
# BOT_TOKEN and WEBHOOK_SECRET are set as secrets, not vars
